
import javax.swing.JFrame;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author toshiba
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jusername = new javax.swing.JLabel();
        jpassword = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jlogin = new javax.swing.JButton();
        jreset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jreg = new javax.swing.JLabel();
        jcmbUT = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jusername.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        jusername.setForeground(new java.awt.Color(0, 255, 204));
        jusername.setText("Username:");
        getContentPane().add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, 40));

        jpassword.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        jpassword.setForeground(new java.awt.Color(0, 255, 204));
        jpassword.setText("Password:");
        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, 40));

        jtxtUser.setBackground(new java.awt.Color(204, 204, 255));
        jtxtUser.setText(" ");
        jtxtUser.setBorder(null);
        jtxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 230, 24));

        jPassword.setBackground(new java.awt.Color(204, 204, 255));
        jPassword.setBorder(null);
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 230, 24));

        jlogin.setBackground(new java.awt.Color(0, 153, 153));
        jlogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\toshiba\\Downloads\\icons for me\\check-double-line (1).png")); // NOI18N
        jlogin.setText("Login");
        jlogin.setBorderPainted(false);
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        getContentPane().add(jlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 90, 30));

        jreset.setBackground(new java.awt.Color(204, 0, 0));
        jreset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jreset.setIcon(new javax.swing.ImageIcon("C:\\Users\\toshiba\\Downloads\\icons for me\\close-line.png")); // NOI18N
        jreset.setText("Reset");
        jreset.setBorderPainted(false);
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });
        getContentPane().add(jreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 90, 30));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 170, 40));

        jreg.setBackground(new java.awt.Color(255, 204, 0));
        jreg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jreg.setForeground(new java.awt.Color(0, 255, 204));
        jreg.setText("Click here to Sign Up");
        jreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jregMouseClicked(evt);
            }
        });
        getContentPane().add(jreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 130, 30));

        jcmbUT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Admin", "Student" }));
        jcmbUT.setBorder(null);
        jcmbUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbUTActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 230, 30));

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("User Type:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 140, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\toshiba\\Downloads\\tech backgrounds\\9.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 460));

        setSize(new java.awt.Dimension(867, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jregMouseClicked
        //ClickheretosignUp button
        Registration rgf = new Registration();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jregMouseClicked

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        //Reset button
       
    }//GEN-LAST:event_jresetActionPerformed

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        //Login Button
                
    }//GEN-LAST:event_jloginActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // Password button
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jtxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserActionPerformed
        
    }//GEN-LAST:event_jtxtUserActionPerformed

    private void jcmbUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbUTActionPerformed
        // User Type button (combo)
    }//GEN-LAST:event_jcmbUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JComboBox<String> jcmbUT;
    private javax.swing.JButton jlogin;
    private javax.swing.JLabel jpassword;
    private javax.swing.JLabel jreg;
    private javax.swing.JButton jreset;
    private javax.swing.JTextField jtxtUser;
    private javax.swing.JLabel jusername;
    // End of variables declaration//GEN-END:variables
}
