/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author toshiba
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRgfirstName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRgfMiddleI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRgfLastN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCmbGender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jrgfAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jrgfCnumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jrgfEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jrgfUserName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jrgfPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jCmbUserType = new javax.swing.JComboBox<>();
        jrgfSignUp = new javax.swing.JButton();
        jrgfreturn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setText("REGISTER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 20));

        jRgfirstName.setText(" ");
        jRgfirstName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jRgfirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRgfirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(jRgfirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 191, 20));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("Middle Initial:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 24));

        jRgfMiddleI.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jRgfMiddleI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRgfMiddleIActionPerformed(evt);
            }
        });
        getContentPane().add(jRgfMiddleI, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 191, -1));

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 20));

        jRgfLastN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jRgfLastN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 191, -1));

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setText("Gender: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 20));

        jCmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Female", "Male" }));
        jCmbGender.setBorder(null);
        jCmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbGenderActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 191, -1));

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 204));
        jLabel6.setText(" Address:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 290, 70, -1));

        jrgfAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jrgfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrgfAddressActionPerformed(evt);
            }
        });
        getContentPane().add(jrgfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 191, -1));

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 204));
        jLabel7.setText("Contact Number: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 130, 20));

        jrgfCnumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jrgfCnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrgfCnumberActionPerformed(evt);
            }
        });
        getContentPane().add(jrgfCnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 191, -1));

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 204));
        jLabel8.setText("Email Address: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jrgfEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jrgfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrgfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jrgfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 191, -1));

        jLabel9.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 204));
        jLabel9.setText("Username:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        jrgfUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jrgfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrgfUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(jrgfUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 191, -1));

        jLabel10.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 204));
        jLabel10.setText("Password:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 90, -1));

        jrgfPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jrgfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 191, -1));

        jLabel11.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 204));
        jLabel11.setText("User Type:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jCmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Student" }));
        jCmbUserType.setBorder(null);
        jCmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbUserTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 191, -1));

        jrgfSignUp.setBackground(new java.awt.Color(0, 153, 255));
        jrgfSignUp.setIcon(new javax.swing.ImageIcon("C:\\Users\\toshiba\\Downloads\\icons for me\\user-add-fill.png")); // NOI18N
        jrgfSignUp.setText("Sign Up");
        jrgfSignUp.setBorderPainted(false);
        jrgfSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrgfSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(jrgfSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 100, 30));

        jrgfreturn.setBackground(new java.awt.Color(255, 0, 0));
        jrgfreturn.setIcon(new javax.swing.ImageIcon("C:\\Users\\toshiba\\Downloads\\icons for me\\arrow-go-back-line.png")); // NOI18N
        jrgfreturn.setText("Return");
        jrgfreturn.setBorder(null);
        jrgfreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrgfreturnActionPerformed(evt);
            }
        });
        getContentPane().add(jrgfreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 100, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\toshiba\\Downloads\\tech backgrounds\\1 (1).jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbGenderActionPerformed

    private void jrgfCnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrgfCnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrgfCnumberActionPerformed

    private void jRgfMiddleIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRgfMiddleIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRgfMiddleIActionPerformed

    private void jrgfreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrgfreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrgfreturnActionPerformed

    private void jRgfirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRgfirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRgfirstNameActionPerformed

    private void jrgfSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrgfSignUpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrgfSignUpActionPerformed

    private void jrgfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrgfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrgfAddressActionPerformed

    private void jrgfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrgfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrgfEmailActionPerformed

    private void jrgfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrgfUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrgfUserNameActionPerformed

    private void jCmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbUserTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCmbGender;
    private javax.swing.JComboBox<String> jCmbUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jRgfLastN;
    private javax.swing.JTextField jRgfMiddleI;
    private javax.swing.JTextField jRgfirstName;
    private javax.swing.JTextField jrgfAddress;
    private javax.swing.JTextField jrgfCnumber;
    private javax.swing.JTextField jrgfEmail;
    private javax.swing.JTextField jrgfPassword;
    private javax.swing.JButton jrgfSignUp;
    private javax.swing.JTextField jrgfUserName;
    private javax.swing.JButton jrgfreturn;
    // End of variables declaration//GEN-END:variables
}
